config/routes.rb
Rails.application.routes.draw do

  root "pills#index"

  devise_for :users
  devise_for :views
  
  resources :pills
  resources :pill_takens
  resources :prescriptions
  resources :vitamins

  
  get ":username/pills" => "users#pills"
  get ":username/vitamins" => "users#vitamins"
  get ":username/pill_takens" => "users#pill_takens"
  get ":username/schedule" => "users#schedule"
  
  #post "/insert_vitamin" => "vitamins#create", as: :new_vitamin # new_vitamin_url and new_vitamin_path
end
 
  #post "/insert_prescription" => "prescriptions#create", as: :new_prescription # new_prescription_url and new_prescription_path
 
  #get "/prescriptions" => "prescriptions#index", as: :prescriptions # prescriptions_url and prescriptions_path
  #get "/prescriptions/:path_id" => "prescriptions#show", as: :prescription # prescription_url() prescription_path() (expects an argument to populate :id segment)
  
  #post "/modify_prescription/:path_id" => "prescriptions#update", as: :edit_prescription # edit_prescription_url and edit_prescription_path() (expects an argument to populate :id segment)

  #get "/delete_prescription/:path_id" => "prescriptions#destroy", as: :delete_prescription # delete_prescription_url and delete_prescription_path() (expects an argument to populate :id segment)

  #post "/insert_pill_taken" => "pill_takens#create", as: :new_pill_taken # new_pill_taken_url and new_pill_taken_path

  #get "/pill_takens" => "pill_takens#index", as: :pills_taken # pills_taken_url and pills_taken_path
  #get "/pill_takens/:path_id" => "pill_takens#show", as: :pill_taken # pill_taken_url and pill_taken_path() (expects an argument to populate :id segment)
  
  #post "/modify_pill_taken/:path_id" => "pill_takens#update", as: :modify_pill_taken # modify_pill_taken_url and modify_pill_taken_path() (expects an argument to populate :id segment)
  
  #get "/delete_pill_taken/:path_id" => "pill_takens#destroy", as: :delete_pill_taken # delete_pill_taken_url and delete_pill_taken_path() (expects an argument to populate :id segment)

  #post "/insert_vitamin" => "vitamins#create", as: :new_vitamin # new_vitamin_url and new_vitamin_path

 # get "/vitamins" => "vitamins#index", as: :vitamins # vitamins_url and vitamins_path
 # get "/vitamins/:path_id" => "vitamins#show", as: :vitamin # vitamin_url and vitamin_path() (expects an argument to populate :id segment)
  
 # post "/modify_vitamin/:path_id" => "vitamins#update", as: :edit_vitamin # edit_vitamin_url and edit_vitamin_path() (expects an argument to populate :id segment)
  
 # get "/delete_vitamin/:path_id" => "vitamins#destroy", as: :delete_vitamin # delete_vitamin_url and delete_vitamin_path() (expects an argument to populate :id segment)

  #post "/insert_pill" => "pills#create", as: :new_pill # new_pill_url and new_pill_path

  #get "/pills" => "pills#index", as: :pills # pills_url and pills_path
  #get "/pill/:path_id" => "pills#show", as: :pill # pill_url and pill_path() (expects an argument to populate :id segment)
  
  #post "/modify_pill/:path_id" => "pills#update", as: :edit_pill # edit_pill_url and edit_pill_path() (expects an argument to populate :id segment)
  
  #get "/delete_pill/:path_id" => "pills#destroy", as: :delete_pill # delete_pill_url and delete_pill_path() (expects an argument to populate :id segment)

  #get "/user_sign_up" => "user_authentication#sign_up_form", as: :sign_up # sign_up_url and sign_up_path   

  #post "/insert_user" => "user_authentication#create", as: :create_user # create_user_url and create_user_path  
      
  #get "/edit_user_profile" => "user_authentication#edit_profile_form", as: :edit_profile # edit_profile_url and edit_profile_path  

  #post "/modify_user" => "user_authentication#update", as: :modify_user # modify_user_url and modify_user_path  
  
  #get "/cancel_user_account" => "user_authentication#destroy", as: :delete_user # delete_user_url and delete_user_path  

  #get "/user_sign_in" => "user_authentication#sign_in_form", as: :sign_in # sign_in_url and sign_in_path  

  #post "/user_verify_credentials" => "user_authentication#create_cookie", as: :create_cookie # create_cookie_url and create_cookie_path  
   
  #get "/user_sign_out" => "user_authentication#destroy_cookies", as: :sign_out # sign_out_url and sign_out_path  
  
#end

app/views/shared/_cdn_assets.html.erb
<meta charset="utf-8">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>

app/views/shared/_flash.html.erb
<div class="alert alert-<%= css_class %> alert-dismissible fade show" role="alert">
  <%= message %>

  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container" >
    <%= link_to "Pills", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Schedule", pill_takens_path, class: "navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to "Inventory", pills_path, class: "navbar-brand" %>    
        </li>
        <li class="nav-item">
          <%= link_to "Vitamin", vitamins_path, class: "navbar-brand" %>    
        </li>
      </ul>
      <ul class="navbar-nav">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>    
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>    
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>    
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>    
        </li>
      <% end %>
      </ul>  
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_notice.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>